  name: Publish Unit Test Results
  uses: EnricoMi/publish-unit-test-result-action@v1
  if: always()
  with:
    files: test-results/**/*.xml

  report_individual_runs: "true"
  check_run_annotations: "all tests"

  runs-on: windows-latest